name: CI

on:
  push:
    branches:
      - feature

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  create_pull_request:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create Pull Request
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = "Automated Pull Request";
            const body = "This is an automated pull request created by GitHub Actions.\nPlease review and merge if everything looks good.";
            const head = "feature";
            const base = "main";
            const { data } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              head,
              base
            });
            console.log(`Pull Request created: ${data.html_url}`);
