name: Auto PR to master

on:
  push:
    branches:
      - '*'

env:
  BRANCH_NAME: ${{ github.head_ref }}

jobs:
  create-pr:
    steps:
      - name: Create Pull Request
        run: |
          PAYLOAD=$(cat <<EOF
            {
              "title": "Title of my PR",
              "body": "Automated PR to ...",
              "head": "${BRANCH_NAME}",
              "base": "main"
            }
          EOF
          )
          curl https://api.github.com/repos/my-user/other-repo/pulls \
            --header "Authorization: token ${ TOKEN }" \
            -H "Content-Type:application/json" \
            -d "$PAYLOAD"
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}