name: Auto Pull Request

on:
  push:
    branches:
      - "feature*"  # Support wildcard matching

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1

      - name: Update author information
        run: echo "${GIT_COMMIT_AUTHOR_NAME}" > AUTHOR

      - name: Raise PR
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "master"
          title: "hi"
          body: |
            This is to show automatic pr