name: Auto Pull Request

on:
  push:
    branches:
      - "feature*"  # Support wildcard matching

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Update author information
        run: echo "${GIT_COMMIT_AUTHOR_NAME}" > AUTHOR

      - name: Raise PR
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "master"
          title: "demo"
          committer: "${GIT_COMMIT_AUTHOR_NAME} <${GIT_COMMIT_AUTHOR_EMAIL}>"
          author: "${GIT_COMMIT_AUTHOR_NAME} <${GIT_COMMIT_AUTHOR_EMAIL}>"
          body: |
            This is to show automatic pr