name: Auto Pull Request

on:
  push:
    branches:
      - "feature*"  # Support wildcard matching

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Show AUTHOR content
        run: cat AUTHOR


