name: Auto Pull Request

on:
  push:
    branches:
      - "feature*"  # Support wildcard matching

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull Request
        uses: diillson/auto-pull-request@latest
        with:
          source_branch: ${{ github.ref }}              # Use the triggered branch as the source
          destination_branch: "master"                  # If blank, default: master
          pr_title: "Pulling ${{ github.ref }} into master"  # Title of the pull request
          pr_body: |
            :crown: *An automated PR*                   # Body of the pull request
          github_token: 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
        env:
          GH_TOKEN: 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