name: Auto PR to master

on:
  push:
    branches:
      - '*'

env:
  BRANCH_NAME: ${{ github.head_ref }}

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Create Pull Request
        run: |
          PAYLOAD=$(cat <<EOF
            {
              "title": "Title of my PR",
              "body": "Automated PR to ...",
              "head": "${BRANCH_NAME}",
              "base": "master"
            }
          EOF
          )
