name: Auto Pull Request

on:
  push:
    branches:
      - "feature*"  # Support wildcard matching

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1

      - name: Update author information
        run: echo "${GIT_COMMIT_AUTHOR_NAME}" > AUTHOR

      - name: Raise PR
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "feature*"
          base: master
          title: "demo"
          committer: "${GIT_COMMIT_AUTHOR_NAME} <${GIT_COMMIT_AUTHOR_EMAIL}>"
          author: "${GIT_COMMIT_AUTHOR_NAME} <${GIT_COMMIT_AUTHOR_EMAIL}>"
          body: |
            This is to show automatic pr
            
          token: ${{ secrets.GITHUB_TOKEN }}
                   - name: Debug Git
                   run: |
                     git --version
                     git status
                     git remote -v
                     # Add more git commands to debug the issue